name: CodeFestival DOMjudge Image Build

on:
  push:
    branches:
      - 'codefes**'
  workflow_dispatch:

jobs:
  image-build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 작업 환경 준비
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          path: domjudge-server
          fetch-depth: 0

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: DOMjudge/domjudge-packaging
          path: domjudge-packaging
          fetch-depth: 0

      - name: Prepare domserver package
        run: tar --exclude-vcs -czf domjudge-packaging/docker/domjudge.tar.gz domjudge-server

      # Docker 빌드 환경 준비
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/codefestival-domserver
          tags: |
            type=ref,event=branch,
            enable=${{ startsWith(github.ref, 'refs/heads/codefes') }},
            value=codefes{0},
            value={{raw}}
            type=sha,prefix=sha-

      # Docker 이미지 빌드 및 GHCR에 푸시
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: domjudge-packaging/docker
          file: domjudge-packaging/docker/domserver/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
